<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../OpenCareer.Application/OpenCareer.Application.csproj" />
    <ProjectReference Include="../OpenCareer.Domain/OpenCareer.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
  </ItemGroup>
</Project>
