<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../OpenCareer.Application/OpenCareer.Application.csproj" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
    <InternalsVisibleTo Include="OpenCareer.Tests" />
  </ItemGroup>
</Project>
